"""配套能力节点模块"""

from .image_upload import (
    UploadToImageHost,
    NODE_CLASS_MAPPINGS as UPLOAD_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as UPLOAD_DISPLAY_MAPPINGS
)

from .batch_image_uploader import (
    BatchImageUploader,
    NODE_CLASS_MAPPINGS as BATCH_UPLOAD_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BATCH_UPLOAD_DISPLAY_MAPPINGS
)

from .image_urls_to_batch import (
    ImageURLsToGrokBatchTasks,
    ImageURLsToVeo3BatchTasks,
    NODE_CLASS_MAPPINGS as URL_TO_BATCH_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as URL_TO_BATCH_DISPLAY_MAPPINGS
)

from .audio_upload import (
    UploadAudioToHost,
    NODE_CLASS_MAPPINGS as AUDIO_UPLOAD_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as AUDIO_UPLOAD_DISPLAY_MAPPINGS
)

from .deepseek_ocr import (
    DeepseekOCRToPrompt,
    NODE_CLASS_MAPPINGS as OCR_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as OCR_DISPLAY_MAPPINGS
)

from .video_download import (
    DownloadVideo,
    PreviewVideo,
    NODE_CLASS_MAPPINGS as VIDEO_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as VIDEO_DISPLAY_MAPPINGS
)

from .csv_reader import (
    CSVBatchReader,
    NODE_CLASS_MAPPINGS as CSV_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CSV_DISPLAY_MAPPINGS
)

from .show_text import (
    ShowText,
    NODE_CLASS_MAPPINGS as SHOW_TEXT_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SHOW_TEXT_DISPLAY_MAPPINGS
)

from .batch_process_logger import (
    BatchProcessLogger,
    NODE_CLASS_MAPPINGS as BATCH_LOGGER_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BATCH_LOGGER_DISPLAY_MAPPINGS
)

from .batch_monitor import (
    BatchProcessMonitor,
    NODE_CLASS_MAPPINGS as BATCH_MONITOR_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BATCH_MONITOR_DISPLAY_MAPPINGS
)

from .realtime_monitor import (
    RealtimeBatchMonitor,
    NODE_CLASS_MAPPINGS as REALTIME_MONITOR_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as REALTIME_MONITOR_DISPLAY_MAPPINGS
)

# 合并所有节点映射
NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(UPLOAD_MAPPINGS)
NODE_CLASS_MAPPINGS.update(BATCH_UPLOAD_MAPPINGS)
NODE_CLASS_MAPPINGS.update(URL_TO_BATCH_MAPPINGS)
NODE_CLASS_MAPPINGS.update(AUDIO_UPLOAD_MAPPINGS)
NODE_CLASS_MAPPINGS.update(OCR_MAPPINGS)
NODE_CLASS_MAPPINGS.update(VIDEO_MAPPINGS)
NODE_CLASS_MAPPINGS.update(CSV_MAPPINGS)
NODE_CLASS_MAPPINGS.update(SHOW_TEXT_MAPPINGS)
NODE_CLASS_MAPPINGS.update(BATCH_LOGGER_MAPPINGS)
NODE_CLASS_MAPPINGS.update(BATCH_MONITOR_MAPPINGS)
NODE_CLASS_MAPPINGS.update(REALTIME_MONITOR_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(UPLOAD_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(BATCH_UPLOAD_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(URL_TO_BATCH_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(AUDIO_UPLOAD_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(OCR_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(VIDEO_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(CSV_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(SHOW_TEXT_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(BATCH_LOGGER_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(BATCH_MONITOR_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(REALTIME_MONITOR_DISPLAY_MAPPINGS)

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
    "UploadToImageHost",
    "BatchImageUploader",
    "ImageURLsToGrokBatchTasks",
    "ImageURLsToVeo3BatchTasks",
    "UploadAudioToHost",
    "DeepseekOCRToPrompt",
    "DownloadVideo",
    "PreviewVideo",
    "CSVBatchReader",
    "ShowText",
    "BatchProcessLogger",
    "BatchProcessMonitor",
    "RealtimeBatchMonitor",
]
